config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('work_space/', include('mailing.urls', namespace='mailing')),
    path('', include('users.urls', namespace='users'))
]

mailing/urls.py
from django.urls import path
from mailing.apps import MailingConfig
from mailing.views import ListMailingRecipient, CreateMailingRecipient, UpdateMailingRecipient, DetailMailingRecipient, \
    DeleteMailingRecipient, ListMessage, CreateMessage, DetailMessage, UpdateMessage, DeleteMessage, ListMailout, \
    CreateMailout, DetailMailout, UpdateMailout, DeleteMailout, MailingAttempt, HomePage

app_name = MailingConfig.name

urlpatterns = [
    path('', HomePage.as_view(), name='home_page'),
    path('client_list/', ListMailingRecipient.as_view(), name='list_client'),
    path('client_create/', CreateMailingRecipient.as_view(), name='create_client'),
    path('client/<int:pk>', DetailMailingRecipient.as_view(), name='detail_client'),
    path('client/<int:pk>/update', UpdateMailingRecipient.as_view(), name='update_client'),
    path('client/<int:pk>/delete', DeleteMailingRecipient.as_view(), name='delete_client'),

    path('message', ListMessage.as_view(), name='list_message'),
    path('message_create/', CreateMessage.as_view(), name='create_message'),
    path('message/<int:pk>', DetailMessage.as_view(), name='detail_message'),
    path('message/<int:pk>/update', UpdateMessage.as_view(), name='update_message'),
    path('message/<int:pk>/delete', DeleteMessage.as_view(), name='delete_message'),

    path('mailout', ListMailout.as_view(), name='list_mailout'),
    path('mailout_create/', CreateMailout.as_view(), name='create_mailout'),
    path('mailout/<int:pk>', DetailMailout.as_view(), name='detail_mailout'),
    path('mailout/<int:pk>/update', UpdateMailout.as_view(), name='update_mailout'),
    path('mailout/<int:pk>/delete', DeleteMailout.as_view(), name='delete_mailout'),

    path('attempt_mailout/<int:pk>', MailingAttempt.as_view(), name='send_mail'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import CustomLoginView, CustomLogoutView, start_page, RegisterView, UserListView, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', start_page, name='start_page'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(next_page='users:start_page'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),

    path('list_users/', UserListView.as_view(), name='list_users'),
    path('user_update/<int:pk>', UserUpdateView.as_view(), name='update_user'),


]

mailing/models.py
from django.db import models
from users.models import CustomUser


class MailingRecipient(models.Model):
    """Получатель рассылки
    Email
    Ф. И. О.
    Комментарий """
    email = models.EmailField(unique=True, verbose_name='email')
    full_name = models.CharField(max_length=100, verbose_name='Имя клиента')
    comment = models.TextField(verbose_name='Комментарий')
    ownership = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, verbose_name='Владелец', null=True, blank=True)

    def __str__(self):
        return f'{self.full_name}'

    class Meta:
        verbose_name = 'Получатель'
        verbose_name_plural = 'Получатели'


class Message(models.Model):
    """Сообщение
    Тема письма
    Тело письма """
    subject_message = models.CharField(max_length=100, verbose_name='Тема письма')
    body_message = models.TextField(verbose_name='Текст сообщения')

    def __str__(self):
        return f'{self.subject_message}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Mailout(models.Model):
    """Рассылка
    Дата и время первой отправки (datetime).
    Дата и время окончания отправки (datetime).
    Статус (строка:'Завершена','Создана','Запущена').
    Сообщение (внешний ключ на модель «Сообщение»).
    Получатели («многие ко многим», связь с моделью «Получатель»)"""

    CREATED = 'created'
    COMPLETED = 'completed'
    LAUNCH = 'launch'

    STATUS_MAILOUT_CHOICES = [
        (CREATED, 'создана'),
        (LAUNCH, 'запущена'),
        (COMPLETED, 'завершена'),
    ]

    datime_first_sending = models.DateTimeField(verbose_name='дата и время первой отправки')
    datime_end_sending = models.DateTimeField(verbose_name='дата и время последней отправки', null=True, blank=True)
    status_mailing = models.CharField(max_length=9, choices=STATUS_MAILOUT_CHOICES, default=CREATED,
                                      verbose_name='статус рассылки')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Сообщение')
    recipient = models.ManyToManyField(MailingRecipient, verbose_name='Получатели')
    ownership = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, verbose_name='Владелец', null=True, blank=True)

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

    def __str__(self):
        return f'{self.message}'


class AttemptToSend(models.Model):
    """Попытка рассылки
    Дата и время попытки (datetime).
    Статус ('Успешно','Не успешно').
    Ответ почтового сервера (текст).
    Рассылка """

    SUCCESSFULLY = 'successfully'
    NOT_SUCCESSFULLY = 'not successful'

    STATUS_ATTEMPT_CHOICES = [
        (SUCCESSFULLY, 'успешно'),
        (NOT_SUCCESSFULLY, 'не успешно'),
    ]

    datime_attempt = models.DateTimeField(auto_now_add=True)
    status_attempt = models.CharField(max_length=14, choices=STATUS_ATTEMPT_CHOICES, default=NOT_SUCCESSFULLY,
                                      verbose_name='статус рассылки')
    mailing_server_response = models.TextField(verbose_name='ответ почтового сервера')
    mailout = models.ForeignKey(Mailout, on_delete=models.CASCADE, verbose_name='рассылка')


    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытки рассылки'

mailing/forms.py
from django import forms
from .models import MailingRecipient, Message, Mailout


class RecipientForms(forms.ModelForm):
    class Meta:
        model = MailingRecipient
        fields = ['full_name', 'email', 'comment']


class MessageForms(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['subject_message', 'body_message']


class MailoutForms(forms.ModelForm):
    class Meta:
        model = Mailout
        fields = ['datime_first_sending', 'datime_end_sending', 'status_mailing', 'message', 'recipient']

mailing/views.py
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView, View, TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RecipientForms, MessageForms, MailoutForms
from .models import MailingRecipient, Message, Mailout, AttemptToSend
from .service import MailingService


class CreateMailingRecipient(LoginRequiredMixin, CreateView):
    model = MailingRecipient
    form_class = RecipientForms
    template_name = 'mailing/recipient_form.html'
    success_url = reverse_lazy('mailing:list_client')

    def form_valid(self, form):
        recipient = form.save()
        user = self.request.user
        recipient.ownership = user
        recipient.save()
        return super().form_valid(form)


class ListMailingRecipient(LoginRequiredMixin, ListView):
    model = MailingRecipient
    template_name = 'mailing/recipient_list.html'
    context_object_name = 'recipients'

    def get_queryset(self):
        queryset = MailingService.get_all_recipient()
        user = self.request.user
        if user.has_perm('users.mailing_permission'):
            return queryset
        else:
            return queryset.filter(ownership=user)


class DetailMailingRecipient(LoginRequiredMixin, DetailView):
    model = MailingRecipient
    form_class = RecipientForms
    template_name = 'mailing/recipient_detail.html'


class UpdateMailingRecipient(LoginRequiredMixin, UpdateView):
    model = MailingRecipient
    form_class = RecipientForms
    template_name = 'mailing/recipient_form.html'
    success_url = reverse_lazy('mailing:list_client')


class DeleteMailingRecipient(LoginRequiredMixin, DeleteView):
    model = MailingRecipient
    template_name = 'mailing/recipient_delete.html'
    success_url = reverse_lazy('mailing:list_client')


class CreateMessage(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForms
    template_name = 'mailing/message_form.html'
    success_url = reverse_lazy('mailing:list_message')


class ListMessage(LoginRequiredMixin, ListView):
    model = Message
    template_name = 'mailing/message_list.html'
    context_object_name = 'messages'

    def get_queryset(self):
        queryset = MailingService.get_all_massage()
        return queryset


class DetailMessage(LoginRequiredMixin, DetailView):
    model = Message
    form_class = MessageForms
    template_name = 'mailing/message_detail.html'


class UpdateMessage(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForms
    template_name = 'mailing/message_form.html'
    success_url = reverse_lazy('mailing:list_message')


class DeleteMessage(LoginRequiredMixin, DeleteView):
    model = Message
    template_name = 'mailing/message_delete.html'
    success_url = reverse_lazy('mailing:list_message')


class CreateMailout(LoginRequiredMixin, CreateView):
    model = Mailout
    form_class = MailoutForms
    template_name = 'mailing/mailout_form.html'
    success_url = reverse_lazy('mailing:list_mailout')

    def form_valid(self, form):
        mailout = form.save()
        user = self.request.user
        mailout.ownership = user
        mailout.save()
        return super().form_valid(form)


class ListMailout(LoginRequiredMixin, ListView):
    model = Mailout
    template_name = 'mailing/list_mailout.html'
    context_object_name = 'mailings'

    def get_queryset(self):
        queryset = MailingService.get_all_mailout()
        user = self.request.user
        if user.has_perm('users.mailing_permission'):
            return queryset
        else:
            return queryset.filter(ownership=user)


class DetailMailout(LoginRequiredMixin, DetailView):
    model = Mailout
    form_class = MailoutForms
    template_name = 'mailing/mailout_detail.html'


class UpdateMailout(LoginRequiredMixin, UpdateView):
    model = Mailout
    form_class = MailoutForms
    template_name = 'mailing/mailout_form.html'
    success_url = reverse_lazy('mailing:list_mailout')


class DeleteMailout(LoginRequiredMixin, DeleteView):
    model = Mailout
    template_name = 'mailing/mailout_delete.html'
    success_url = reverse_lazy('mailing:list_mailout')


class MailingAttempt(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        # template_name = 'mailing/attempt_mailing.html'
        mailout = get_object_or_404(Mailout, pk=pk)
        return render(request, 'mailing/attempt_mailing.html', {"mailout": mailout})

    def post(self, request, pk, *args, **kwargs):
        mailout = get_object_or_404(Mailout, pk=pk)
        if mailout.status_mailing:
            print(mailout.status_mailing)
            recipients = mailout.recipient.all()
            mailout.status_mailing = 'запущена'
            for recipient in recipients:
                try:
                    send_mail(
                        subject=mailout.message.subject_message,
                        message=mailout.message.body_message,
                        from_email="django.formeiling@yandex.ru",
                        recipient_list=[recipient.email]
                    )

                    AttemptToSend.objects.create(
                        status_attempt='успешно',
                        mailing_server_response='Сообщение успешно отправлено',
                        mailout=mailout
                    )

                except Exception as exception:
                    AttemptToSend.objects.create(
                        status_attempt='не успешно',
                        mailing_server_response=str(exception),
                        mailout=mailout
                    )

        mailout.status_mailing = 'завершена'
        mailout.save()
        return redirect('mailing:list_mailout')


class HomePage(LoginRequiredMixin, TemplateView):
    template_name = 'mailing/home_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['quantity_mailing'] = len(Mailout.objects.all())
        context['launch_mailing'] = Mailout.objects.filter(status_mailing='запущена').count()
        context['quantity_recipient'] = MailingRecipient.objects.distinct().count()
        return context

mailing/templates/mailing/attempt_mailing.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-7">
            <div class="card">
                <div class="card-body">
                    <form method='post'>
                        {% csrf_token %}
                        <p>Хотите отправить рассылку: "{{mailout}}"?</p>
                        <p>Статус рассылки: "{{mailout.status_mailing}}"?</p>
                        <p>Тема рассылки: "{{mailout.message.subject_message}}"?</p>
                        <p>Текст писма: "{{mailout.message.body_message}}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a class="btn btn-primary" href="{% url 'mailing:list_mailout' %}" role="button">Отменить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/home_page.html
{% extends 'mailing/base.html' %}

{% block content %}
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">Колличество запущенных рассылок</th>
        <th scope="col">{{launch_mailing}}</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Всего рассылок</td>
        <td>{{quantity_mailing}}</td>
    </tr>
    <tr>
        <td>Количество получателей</td>
        <td>{{quantity_recipient}}</td>
    </tr>
    </tbody>
</table>
{% endblock %}


{% for mailout in mailings %}
<div class="card">
    <div class="card-body">
        {{mailout.message.subject_message}}
        <a class="btn btn-success " href="{% url 'mailing:send_mail' mailout.pk  %}"
           role="button">Отправить</a>
        <a class="btn btn-primary" href="{% url 'mailing:detail_mailout' mailout.pk  %}"
           role="button">Посмотреть</a>
        <a class="btn btn-primary" href="{% url 'mailing:update_mailout' mailout.pk  %}"
           role="button">Редактировать</a>
        <a class="btn btn-outline-danger " href="{% url 'mailing:delete_mailout' mailout.pk  %}"
           role="button">Удалить</a>
    </div>
</div>
{% endfor %}

mailing/templates/mailing/mailout_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-2">
            <div class="card">
                <div class="card-body">
                    <form method='post'>
                        {% csrf_token %}
                        <p>Хотите удалить рассылку, на тему: "{{object.message.subject_message}}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a class="btn btn-primary" href="{% url 'mailing:list_mailout' %}" role="button">Отменить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailout_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="card shadow-sm">
    <div class="card-body">
        <p class="card-text">Тема письма расслыки: {{object.message.subject_message}}</p>
        <p class="card-text">Текст письма рассылки: {{object.message.body_message}}</p>
        <p class="card-text">Дата и время первой отправки: {{object.datime_first_sending}}</p>
        <p class="card-text">Дата и время окончания отправки: {{object.datime_end_sending}}</p>
        <p class="card-text">Статус: {{object.status_mailing}}</p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a class="btn btn-primary" href="{% url 'mailing:list_mailout'%}"
                   role="button">Назад</a>
            </div>

        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailout_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="card">
    <div class="card-body">
        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">
                {% if object %}
                Сохранить
                {% else %}
                Создать
                {% endif %}
            </button>
            <a class="btn btn-success" href="{% url 'mailing:list_mailout' %}" role="button">Назад</a>
        </form>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailout_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Рассылки</h1>
    <a class="btn btn-primary" href="{% url 'mailing:create_mailout'%}"
       role="button">Создать рассылку </a>
</div>

{% for mailout in mailings %}
<div class="card">
    <div class="card-body">
        {{mailout.message.subject_message}}
        <a class="btn btn-success " href="{% url 'mailing:send_mail' mailout.pk  %}"
           role="button">Отправить</a>
        <a class="btn btn-primary" href="{% url 'mailing:detail_mailout' mailout.pk  %}"
           role="button">Посмотреть</a>
        <a class="btn btn-primary" href="{% url 'mailing:update_mailout' mailout.pk  %}"
           role="button">Редактировать</a>
        <a class="btn btn-outline-danger " href="{% url 'mailing:delete_mailout' mailout.pk  %}"
           role="button">Удалить</a>
    </div>
</div>
{% endfor %}
{% endblock %}

mailing/templates/mailing/message_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-2">
            <div class="card">
                <div class="card-body">
                    <form method='post'>
                        {% csrf_token %}
                        <p>Хотите удалить сообщение, на тему: "{{object.subject_message}}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a class="btn btn-primary" href="{% url 'mailing:list_message' %}" role="button">Отменить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="card shadow-sm">
    <div class="card-body">
        <p class="card-text">Имя: {{object.subject_message}}</p>
        <p class="card-text">Почта: {{object.body_message}}</p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a class="btn btn-primary" href="{% url 'mailing:list_message'%}"
                   role="button">Назад</a>
            </div>

        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="card">
    <div class="card-body">
        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">
                {% if object %}
                Сохранить
                {% else %}
                Создать
                {% endif %}
            </button>
            <a class="btn btn-success" href="{% url 'mailing:list_message' %}" role="button">Назад</a>
        </form>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/recipient_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-2">
            <div class="card">
                <div class="card-body">
                    <form method='post'>
                        {% csrf_token %}
                        <p>Хотите удалить клиента? "{{object.full_name}}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a class="btn btn-primary" href="{% url 'mailing:list_client' %}" role="button">Отменить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/recipient_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="card shadow-sm">
    <div class="card-body">
        <p class="card-text">Имя: {{object.full_name}}</p>
        <p class="card-text">Почта: {{object.email}}</p>
        <p class="card-text">комментарий: {{object.comment}}</p>
        <p class="card-text">владелец записи: {{object.ownership}}</p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a class="btn btn-primary" href="{% url 'mailing:list_client'%}"
                   role="button">Назад</a>
            </div>

        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/recipient_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="card">
    <div class="card-body">
        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">
                {% if object %}
                Сохранить
                {% else %}
                Создать
                {% endif %}
            </button>
            <a class="btn btn-success" href="{% url 'mailing:list_client' %}" role="button">Назад</a>
        </form>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/recipient_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Получатели</h1>
    <a class="btn btn-primary" href="{% url 'mailing:create_client'%}"
       role="button">Создать клиента </a>
</div>
{% for recipient in recipients %}
<div class="card">
    <div class="card-body">
        {{recipient.full_name}}
        <a class="btn btn-primary" href="{% url 'mailing:detail_client' recipient.pk  %}"
           role="button">Посмотреть</a>
        <a class="btn btn-primary" href="{% url 'mailing:update_client' recipient.pk  %}"
           role="button">Редактировать</a>
        <a class="btn btn-danger" href="{% url 'mailing:delete_client' recipient.pk  %}"
           role="button">Удалить</a>
    </div>
</div>
{% endfor %}
{% endblock %}