config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('work_space/', include('mailing.urls', namespace='mailing')),
    path('', include('users.urls', namespace='users'))
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import CustomLoginView, CustomLogoutView, start_page, RegisterView, UserListView, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', start_page, name='start_page'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(next_page='users:start_page'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),

    path('list_users/', UserListView.as_view(), name='list_users'),
    path('user_update/<int:pk>', UserUpdateView.as_view(), name='update_user'),


]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True, verbose_name='email')
    phone_number = models.CharField(max_length=25, null=True, blank=True, verbose_name='номер телефона')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'username']

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            ('mailing_permission', 'mailing pemission'), #блокировка(просмотра редакции) рассылок
            ('disabling_users', 'disabling users'), #блокировка пользователей
            ('disabling_mailing', 'disabling mailing'), #блокировка рассылок
        ]

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm

from .models import CustomUser


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class CustomUserCreationForm(UserCreationForm):
    phone_number = forms.CharField(max_length=15, required=False,
                                   help_text='Необязательное поле. Введите ваш номер телефона.')

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('email', 'first_name', 'last_name', 'username', 'password1', 'password2',)

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        if phone_number and not phone_number.isdigit():
            raise forms.ValidationError('Номер телефона должен содержать только цифры.')
        return phone_number


class CustomUserUpdateForm(StyleFormMixin, ModelForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'username', 'is_active')

users/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from users.forms import CustomUserCreationForm, CustomUserUpdateForm
from users.models import CustomUser


def start_page(request):
    return render(request, template_name='users/start_page.html')


class CustomLoginView(LoginView):
    template_name = 'users/login.html'


class CustomLogoutView(LogoutView):
    template_name = 'users/logout.html'


class RegisterView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')


class UserListView(LoginRequiredMixin, ListView):
    model = CustomUser
    template_name = 'users/users_list.html'
    context_object_name = 'users_objects'


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserUpdateForm
    template_name = 'users/user_form.html'
    success_url = reverse_lazy('users:list_users')

users/templates/users/login.html
{% extends "mailing/base.html" %}

{% block content %}
  <h2>Вход</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти</button>
  </form>
{% endblock %}

users/templates/users/logout.html
{% extends "mailing/base.html" %}

{% block content %}
<h2>Вы вышли из системы</h2>
<p>Спасибо, что воспользовались нашим сайтом. Вы успешно вышли из системы.</p>
<a href="{% url 'users:start_page' %}">Войти снова</a>
{% endblock %}

users/templates/users/register.html
{% extends "mailing/base.html" %}

{% block content %}
<h2>Регистрация</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зарегистрироваться</button>
</form>
{% endblock %}

users/templates/users/start_page.html
{% extends "mailing/base.html" %}

{% block content %}
    <h1>Это начальная страница сайта по моей курсовой.</h1>
    <p class="lead">Нужно зарегистрироваться или авторизоваться.</p>
    <p class="lead">
      <a href="{% url 'users:login' %}" class="btn btn-lg btn-light fw-bold border-white bg-white">Авторизоваться</a>
      <a href="{% url 'users:register' %}" class="btn btn-lg btn-light fw-bold border-white bg-white">Зарегистрироваться</a>
    </p>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="card">
    <div class="card-body">
        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">
                {% if object %}
                Сохранить
                {% else %}
                Создать
                {% endif %}
            </button>
            <a class="btn btn-success" href="{% url 'users:list_users'%}" role="button">Назад</a>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/users_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Пользователи</h1>
</div>
{% for user in users_objects %}
<div class="card">
    <div class="card-body">
        {{user.username}}
        <a class="btn btn-primary" href="{% url 'users:update_user' user.pk  %}"
           role="button">Редактировать</a>
    </div>
</div>
{% endfor %}
{% endblock %}

<!--{% url 'users:update_user' users_objects.pk  %}-->